#ifndef MODEL_H
#define MODEL_H

#include <stdint.h>

#define MODEL_ARENA_BYTES 208
#define MODEL_INPUT_BYTES 64
#define MODEL_OUTPUT_BYTES 36

/* input: (1, 8, 8) uint8, scale=0.015684135258197784, zero_point=127
 * output: (4, 3, 3) uint8, scale=0.06913453340530396, zero_point=136
 * Generated by codegen.py (naive conv2d) from the Phase 0
 * quantized model (qparams.json) and the Phase 2 memory plan.*/
void model_run(const uint8_t *input, uint8_t *output);

#endif /* MODEL_H */
